# Generated by Django 5.1.2 on 2024-11-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0003_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(default='images/capa.jpg', upload_to='imagens/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='imagens/alan_suporte_ti.jpg', upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
