# Generated by Django 5.1.2 on 2024-11-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0004_projeto_capa_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('mensagem', models.TextField(max_length=1000)),
            ],
        ),
    ]
