# Generated by Django 5.1.2 on 2024-11-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0005_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
