# Generated by Django 5.1.2 on 2024-11-29 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0006_alter_contato_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(help_text='Digite apenas números, sem espaços ou caracteres especiais', max_length=15, validators=[django.core.validators.RegexValidator(message='O telefone deve conter apenas números', regex='^\\d+$')]),
        ),
    ]
