# Generated by Django 5.1.2 on 2024-12-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0008_alter_contato_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('idCurso', models.IntegerField()),
                ('curso', models.CharField(max_length=100)),
                ('valorPago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dtCompra', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='vagas',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
    ]
